language: node_js
node_js:
  - '8'

before_script:
  - npm install

script: gulp

before_deploy:
  - sed -i -e "s|__OPENWEATHERMAP_APIKEY__|$OPENWEATHERMAP_APIKEY|g" js/config.template.js
  - sed -i -e "s|__GOOGLEANALYTICS_APIKEY__|$GOOGLEANALYTICS_APIKEY|g" js/config.template.js
  - mv js/config.template.js js/config.js
  - rm -rf node_modules

deploy:
  provider: s3
  access_key_id: AKIAJVLQVM67YCKTWHGQ
  secret_access_key:
    secure: Z1JEL5CZgIbYebfQ0I3YHS2LdymyvVhNPa9pkbIB+TBq+yizLHMyrq5MCdx1/800w4ffuuDDHRBFai7j6vxKYhyZ/mpnQKn5okT6xa0xe7dhXnkz9QrgytWJznc36mLj3IHoWa0cphMh8ejcX6TK7b5bBG3C7C2Ld0O8r5vtbsJTF93ugrYJHZLhKp2OUVUiJgqR7J1oYiiM1Jl2VynZQWAOR54n9HQOQgG70YYnwltGuuCYf9EabcGswNC40nYUIZZ2nRZF6qWROdaG4qMCz57yf5Pmv3S6nCfWxqjoAeLYj4fotpz5k0oPiWOoV6dct1uD3UPIQz2/HZu9z7I9f+5hmUfpy11978iHm9gMQLlaeTc/8Iyc4r1Kj1EzugkUX2k7Wl4a57mdGW+DEJ+SLHXPaJgrW2hFjMMIAYN7ZA0m0Mas081wcO2cp5IyEV6qy2ufowYoqiOBmvu4OlfrrSRF9uGbiX22TZsIfLsiQjMN6CeAuS8qIs7tMYMxrDybk2w+yh/AQvl9Cxb1psoUNQt+eP+UsPFJbCcjIwOS4wd+Y6zu7kDkSa98IJl8lpXIsxYOjd7Fyhj+hs7yaQVg81ym78v1DwKTPxstfvuujlswqt57OCxmfFmv/0CEVdOTdfbaHr+8gRHt3a+9+9FIKBBvtTRV3UFqtmlspPiuu78=
  bucket: my-weather-app
  acl: public_read
  on:
    repo: claudiazanetel/weather-app
    branch: master
  skip_cleanup: true

env:
  global:
    - secure: JqRf7pwbJhXHlr230/fQh3ayw5bEp5Mh+8+LL+QUbOCCf30lWeh5CUyckqLY1PXfuqv7OKaEqM6OfMjmW1eKfzveQRSuCCEr3UC9Y6Ys/eljO+4OZUlHh28TZKbFW1mI74+jvcPBisyGwMNsDFZx/Vcu/sj9+hSFS0pSMQ8kRi/2LIcgIrzVxKz2aRtk6qCbx9rfN9MePNv+sX8qz/b4YgQSC03HteWXUIF+FONLXztfGnKmSyHtKA5jxCtFWBGBIOFSAUxCqOeprXRTIytE5+fHrouIzC95IZHXq61Ip++fogEXSKlWLrUAKQXgAsMRKh8HDYhVvv0RCsqrNb0BatKPfSb9+tkBLn4yNR0ulvuXSUGERzCfmUlZFaRcn8J/qryErgTmvii7dtU8duZjh6nIhlylDqEjtAe+DN9CO6/YtiMRU6UAzUDErRFaZZVVF0YARDmSrTq9qS7g2CMpbabwn3sY2Fw66JfKXbWgAeK8d/SIRrk5sgJkAV5N0RHJliR3aRs2fI4j4ZRd0Odb2XhkvgsPDBqbRIFNTbJ5riL+4P1C7Mp+b3qjNdror9KZqmy3aXsqCB9GIUT8p3Av/VGa1VpkeR8BTDLYsdN/Cdf2RZ+9GCp38u/6kmAMtAjnwFax09ThvKn72IaXmNoD60T8K0/0X59AYu5kRqAieAM=
    - secure: T9IRcy7NBN/UgOKUK9XUVPoZtZ+1O8CrFz9PYm4OO90iLJQ/V1M/aEK7KFOa/4PFZnrBX3OYhkPCwGRdxMHTsk5Ah3OEfyqsLNmKgTWr5JS+ShBs62sVg9tAPvGxoUoEUU/gzWR7ZZqCsz7/f5hS9jaTZwShsr2SLkYFrYJwyTME1voYJeY5Cc2SSpirlb1fcNh4drBDLPXTsMrucKkXJEfYUH3YjWbPOmC75UTuqhVhm5X2SHqrthlin8ON2CaYVherqjMX+jX1MB4Uz1hwBt/BTK9O8Aho45XbWAS7VU7XkIqzdQmsNJ7eLWtofSti6DTPrLK3+NA6wfMd02qyjKBqfhVbN7yC+WrsvERjJnb11VyXywmNZWuQF0GmP6oZoj+6OLFklNHp+Q3BQRfO1GeW4iuYwpn97nLmMkuAIytbthHc0oXfnCFppKnGAGlCEr/indLJALyKIyhHOvIXzwjUx9gnzH2ZemNFzdARwbUiFzqi1SkdW/JjhRNtd0tvVNcDDUWsC9NMHHDiZGY3rZ7x8nzTWBzJumIv/+TtvRzG9aFJDXvMhhJm0cYHsi0wRoXGqOQNOSUKTLyqFVXO/plJTd1V0nWflPhsibYucVAw8nSYHh0LiLNAJ3tp2JmQbPM1pkMKBQwTK48UlEUI+MNoyDjaMG6nI9mH1ANAK/o=
